### ISSUE TITLE
Why pytorch is better than tensorflow for Geometric deep learning

### ISSUE THREAD

**Issue by WrathofBhuvan11** [yongqyu/MolGAN-pytorch#1]
I generally use tensorflow,keras for my projects which was generally related to Euclidean space/ grids till now... Now I have a project related to Graph or geometric learning and I found tht pytorch easily supports Geometric deep learning than tensorflow... Can u give Ur opinion related to this... Should I shift my framework from keras - TF to PyTorch ?

**Comment by yongqyu** [comment]
Hi, WrathofBhuvan11.
First, I'm sorry for my lateness.
About your question, I do not think pytorch supports more easily for geometric deeplearning than tf. 
My implementation also uses a simple module provided by both frameworks. 
However, I have seen a lot of usage of the GDL library using pytorch like [pytorch geometric](https://rusty1s.github.io/pytorch_geometric/build/html/index.html).
There seems to be a similar library in tf.
If you can not find it, you may want to refer to it.

Thanks.
