### ISSUE TITLE
I get a problem when i test label2onehot function

### ISSUE THREAD

**Issue by zhengchu1994** [yongqyu/MolGAN-pytorch#2]
Here is the code:
`data = SparseMolecularDataset()
data.load('data/gdb9_9nodes.sparsedataset')
mols, _, _, a, x, _, _, _, _  = data.next_train_batch(16)
a = torch.from_numpy(a).to('cpu').long() 
a_tensor = label2onehot(a, 4)
`
and i have a error happended:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-84-d85ad6d28295> in <module>
----> 1 a_tensor = label2onehot(a, 4)

<ipython-input-83-9a407987c96c> in label2onehot(labels, dim)
      7     print(labels.unsqueeze(-1).shape)
      8     print(len(out.size())-1)
----> 9     out.scatter_(len(out.size())-1,labels.unsqueeze(-1),1.)
     10     return out

RuntimeError: Invalid index in scatter at c:\a\w\1\s\windows\pytorch\aten\src\th\generic/THTensorEvenMoreMath.cpp:549

Can u tell me what happend?  I have no idea.

**Comment by yongqyu** [comment]
I have not experienced this problem. 
It seems to be a problem with `torch.scatter_()` like an error message.
Share the values of `len(out.size ()) - 1 `and `labels.unsqueeze(-1).shape` on lines 7 and 8 to me, please.
In addition, it would be helpful to know the shape of the `out`.

Thank you.

**Comment by zhengchu1994** [comment]
`    def label2onehot(labels, dim):
        """Convert label indices to one-hot vectors."""
        # list(labels.size()) 返回labels的shape
        out = torch.zeros(list(labels.size())+[dim]).to('cpu')
        print(out.shape)
        # labels.unsqueeze(-1) 在最后增加一个维度；torch.Size([10, 9, 9]) to torch.Size([10, 9, 9, 1])
        print(labels.unsqueeze(-1).shape)
        print(len(out.size())-1)
        out.scatter_(len(out.size())-1,labels.unsqueeze(-1),1.)
        return out`


This function print blow:

torch.Size([16, 9, 9, 4])
torch.Size([16, 9, 9, 1])
3

and
`a = torch.from_numpy(a).to('cpu').long() 
print(a.shape)`

torch.Size([16, 9, 9])

**Comment by yongqyu** [comment]
If so, you need to check the value inside `labels` .
If the value is greater than `3`, the problem will occur.

**Comment by zhengchu1994** [comment]
That's why i get the error,  `labels` has some `4` values. Thanks for your timely help.
