### ISSUE TITLE
GraphVAE

### ISSUE THREAD

**Issue by InvincibleIRMan** [yongqyu/MolGAN-pytorch#4]
Hi, First of all I would like to thank you for the nice implementation. It facilitate a lot my life!

Second, I have seen the author of the paper is reimplement the GraphVAE in his repository. I wonder to know if you have done this in pytorch? if not do you know any repository which implement GraphVAE in pytorch?

Thank you,
Sadegh

**Comment by yongqyu** [comment]
Thank you for your attention.
I did not find a repository built with pytorch. 
I'll let you know if I can implement it.

Thanks.

**Comment by InvincibleIRMan** [comment]
You can find the tensor flow implementation of the Graph VAE here.

Thank you very much for your fast considerations!

Sadegh

**Comment by InvincibleIRMan** [comment]
https://github.com/nicola-decao/MolGAN/blob/master/models/vae.py
