### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by yyou1996** [yongqyu/MolGAN-pytorch#9]
Hi,

Thanks greatly for your pyt implementation. Nice work! A small question, I wonder what is the estimated training time in what GPU of your code?

**Comment by yongqyu** [comment]
Hi, You.

First of all, I would like you to know that this code did not fully implement the original paper.
I've only experimented with training in a gpu environment for less than an hour, and with this I got enough results.
I hope this helps you.

Thanks.

**Comment by yyou1996** [comment]
Thank you for your reply.
